version: 0.2
phases:
  build:
    commands:
      - mvn package
      - aws cloudformation package --template-file serverless.yml --s3-bucket anagram-store-bucket-0803 --output-template-file outputtemplate.yml
artifacts:
  files:
    - target/anagram-service-1.0-SNAPSHOT-lambda-package.zip
    - serverless.yml
    - outputtemplate.yml
