version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - npm -g install serverless
      - mvn package
      - serverless deploy
artifacts:
  files:
    - target/anagram-service-1.0-SNAPSHOT-lambda-package.zip
    - serverless.yml
