version: 0.2
phases:
  build:
    commands:
      - npm -g install serverless
      - mvn package
      - mkdir -p target/dev
      - serverless package --package target/dev
artifacts:
  files:
    - target/**/*
    - serverless.yml
    - deploy.sh
