service: anagramstore

provider:
  name: aws
  runtime: java8
  memorySize: 1512
  timeout: 60
  stage: ${opt:stage,'dev'}
  region: ${opt:region, 'us-west-2'}
  profile: ${opt:profile, "default"}
  endpointType: REGIONAL

resources:
  Description: Example Anagram Store API written with SpringBoot with the aws-serverless-java-container library

package:
  individually: true

functions:
  SpringBootAnagramStoreApi:
    package: 
      artifact: target/anagram-store-1.0-SNAPSHOT-lambda-package.zip
    handler: com.anagram.serverless.springboot.StreamLambdaHandler::handleRequest
    events:
      - http:
          path: /{proxy+}
          method: ANY